// ============================================================
// 礼物侦探 · 数据层
// 16型人格定义 + 礼物数据库
// ============================================================

// ---------- 16 型人格画像 ----------
const PERSONAS = {
  EMLS: { name: "派对小太阳", en: "Sunny Host", emoji: "🥂",
    tagline: "朋友圈照片最多，请客最积极",
    desc: "TA 是房间里最亮的那颗星，天生擅长把人聚在一起，从来不让气氛冷场。" },
  EMLW: { name: "潮流冒险家", en: "Trend Scout", emoji: "🛼",
    tagline: "新店首发日常打卡，爱晒新奇物",
    desc: "TA 永远比朋友圈早三个月种草，对一切新鲜事物都有雷达。" },
  EMRS: { name: "高光主理人", en: "Polished Lead", emoji: "💼",
    tagline: "职场稳扎稳打，讲究体面",
    desc: "TA 把生活当作品在打磨，每一个细节都要经得起放大。" },
  EMRW: { name: "玩物鉴赏家", en: "Curious Collector", emoji: "🎮",
    tagline: "什么新玩具都要第一个拥有",
    desc: "TA 是行走的新品发布会，桌面永远在迭代。" },
  EALS: { name: "氛围感大师", en: "Vibe Maker", emoji: "🕯️",
    tagline: "桌面永远有鲜花和蜡烛",
    desc: "TA 把日常过成电影，灯光、香气、配色一样都不能少。" },
  EALW: { name: "文艺冒险王", en: "Artsy Nomad", emoji: "🎨",
    tagline: "看展+citywalk+独立音乐节常客",
    desc: "TA 的周末日程比工作日还满，永远在追逐下一场灵感。" },
  EARS: { name: "仪式感企划", en: "Ritual Planner", emoji: "🎁",
    tagline: "生日纪念日提前一个月准备",
    desc: "TA 把每个值得纪念的日子都做成纪录片。" },
  EARW: { name: "跨界玩家", en: "Crossover Player", emoji: "🧩",
    tagline: "什么都懂一点，爱跨圈层交友",
    desc: "TA 是社交场里的万能接口，能和任何人聊上半小时。" },
  IMLS: { name: "温柔治愈系", en: "Gentle Healer", emoji: "🍵",
    tagline: "说话软、爱照顾人，自己却低需求",
    desc: "TA 是朋友圈里那个永远在递纸巾的人，对自己却最克制。" },
  IMLW: { name: "隐秘文青", en: "Quiet Poet", emoji: "📖",
    tagline: "日记本永远写不完，爱小众电影",
    desc: "TA 的内心世界比朋友圈丰富一百倍，只对极少数人打开。" },
  IMRS: { name: "极简高效派", en: "Minimalist Pro", emoji: "⚪",
    tagline: "东西少而精，讨厌花里胡哨",
    desc: "TA 信奉 less is more，每一件物品都要通过严格面试。" },
  IMRW: { name: "深宅极客", en: "Deep Geek", emoji: "⌨️",
    tagline: "一个人能研究一个领域到精通",
    desc: "TA 是垂直领域的隐藏大佬，能为一个细节研究三天三夜。" },
  IALS: { name: "慢生活家", en: "Slow Soul", emoji: "🌿",
    tagline: "周末种花做饭，岁月静好人设",
    desc: "TA 把日子过得像散文诗，时间在 TA 身上走得格外温柔。" },
  IALW: { name: "赛博诗人", en: "Cyber Dreamer", emoji: "👾",
    tagline: "二次元/虚拟偶像/独立游戏爱好者",
    desc: "TA 的精神故乡不在地球，在某个像素和代码构成的次元。" },
  IARS: { name: "古典守护者", en: "Classic Keeper", emoji: "🏺",
    tagline: "穿衣守旧、喜欢传统工艺",
    desc: "TA 相信经过时间考验的东西才有真正的分量。" },
  IARW: { name: "暗夜探索者", en: "Midnight Explorer", emoji: "🌙",
    tagline: "深夜活跃，爱小众神秘向话题",
    desc: "TA 在白天是普通人，到了深夜才开始真正运转。" }
};

// ---------- 12 道人格题 ----------
// 每题：{ dim: 维度, options: [{label, value}], }  value = "E" / "I" 等
const QUESTIONS = [
  // E/I 能量维度
  { dim: "EI", q: "TA 过生日最想要的庆祝方式是？",
    options: [
      { label: "大家一起办派对，越热闹越好", value: "E" },
      { label: "和最亲近的 1–2 人安静吃饭", value: "I" }
    ]},
  { dim: "EI", q: "周末 TA 更常出现在？",
    options: [
      { label: "热闹的街区、livehouse、聚会", value: "E" },
      { label: "家里、咖啡馆角落、图书馆", value: "I" }
    ]},
  { dim: "EI", q: "收到礼物后 TA 的反应更像？",
    options: [
      { label: "立刻发朋友圈或群里炫耀一下", value: "E" },
      { label: "私下默默收好、单独谢你", value: "I" }
    ]},
  // M/A 审美维度
  { dim: "MA", q: "TA 的房间或工位更接近？",
    options: [
      { label: "干净清爽、东西很少", value: "M" },
      { label: "摆件、挂画、氛围灯一大堆", value: "A" }
    ]},
  { dim: "MA", q: "TA 买东西最在意？",
    options: [
      { label: "实用耐用、不花哨", value: "M" },
      { label: "好看、能拍照、有故事感", value: "A" }
    ]},
  { dim: "MA", q: "TA 的穿搭风格更像？",
    options: [
      { label: "基础色系、合身剪裁", value: "M" },
      { label: "有设计感、敢撞色或复古", value: "A" }
    ]},
  // L/R 决策维度
  { dim: "LR", q: "TA 选礼物给别人时更在意？",
    options: [
      { label: "有没有心意、有没有故事", value: "L" },
      { label: "对方是不是真的用得上", value: "R" }
    ]},
  { dim: "LR", q: "TA 更容易被打动的瞬间？",
    options: [
      { label: "你记住了 TA 一个小细节", value: "L" },
      { label: "你帮 TA 省了时间或解决了问题", value: "R" }
    ]},
  { dim: "LR", q: "如果只能二选一，TA 会选？",
    options: [
      { label: "一封手写长信", value: "L" },
      { label: "一张高额购物卡", value: "R" }
    ]},
  // S/W 生活态度维度
  { dim: "SW", q: "TA 对新品牌的态度？",
    options: [
      { label: "经过时间检验的经典款更放心", value: "S" },
      { label: "越新越小众越兴奋", value: "W" }
    ]},
  { dim: "SW", q: "TA 的旅行偏好？",
    options: [
      { label: "路线规划好、住熟悉的连锁", value: "S" },
      { label: "临时起意、爱去冷门地", value: "W" }
    ]},
  { dim: "SW", q: "TA 最近一次主动尝试的新事物？",
    options: [
      { label: "想不太起来", value: "S" },
      { label: "立刻能说出 2–3 个", value: "W" }
    ]}
];

// ---------- 关系 & 预算 ----------
const RELATIONS = [
  { id: "lover",    label: "恋人",      emoji: "💌", hint: "把心意拉满" },
  { id: "friend",   label: "朋友",      emoji: "🫂", hint: "送一份默契" },
  { id: "family",   label: "家人",      emoji: "🏠", hint: "藏在日常里" },
  { id: "colleague",label: "同事",      emoji: "☕", hint: "得体不越界" },
  { id: "crush",    label: "暗恋对象",  emoji: "🌷", hint: "刚刚好的距离" }
];

const BUDGETS = [
  { id: "b1", label: "100 以下",    min: 0,    max: 100 },
  { id: "b2", label: "100–300",     min: 100,  max: 300 },
  { id: "b3", label: "300–500",     min: 300,  max: 500 },
  { id: "b4", label: "500–1000",    min: 500,  max: 1000 },
  { id: "b5", label: "1000+",       min: 1000, max: 99999 }
];

// ---------- 礼物数据库 ----------
// 字段：name, price, emoji, tags(关键词，用于开放题匹配),
// personas(适配的人格代号数组), relations(适配关系), reason(推荐理由模板)
const GIFTS = [
  // ===== 派对/外向/聚会型 =====
  { name: "香槟金气泡礼盒", searchQuery: "香槟礼盒 起泡酒", priceMin: 90, priceMax: 230, priceTypical: 120, priceLabel: "¥90–230", emoji: "🍾",
    tags: ["聚会","派对","庆祝","酒","气泡水"],
    personas: ["EMLS","EMRS","EALS","EARS","EARW"],
    relations: ["lover","friend","colleague"],
    reason: "TA 是天生的氛围发起人，让 TA 在下一次小聚里成为开场担当。" },
  { name: "便携蓝牙音箱（设计师款）", searchQuery: "蓝牙音箱 便携 设计师", priceMin: 300, priceMax: 800, priceTypical: 500, priceLabel: "¥300–800", emoji: "🔊",
    tags: ["音乐","聚会","派对","户外","露营"],
    personas: ["EMLS","EMLW","EARW","EALW"],
    relations: ["lover","friend","family"],
    reason: "走到哪里热闹就到哪里，正好配 TA 这种自带 BGM 的体质。" },
  { name: "复古桌游礼盒", searchQuery: "桌游礼盒 派对游戏", priceMin: 20, priceMax: 90, priceTypical: 49, priceLabel: "¥20–90", emoji: "🎲",
    tags: ["桌游","聚会","朋友","派对"],
    personas: ["EMLS","EARW","EMRW"],
    relations: ["friend","colleague","family"],
    reason: "下一次聚会的破冰神器，TA 一定会拉着所有人玩到深夜。" },

  // ===== 潮流/新奇/小众 =====
  { name: "设计师联名帆布包", searchQuery: "设计师联名 帆布包", priceMin: 60, priceMax: 200, priceTypical: 120, priceLabel: "¥60–200", emoji: "👜",
    tags: ["设计","潮流","穿搭","包"],
    personas: ["EMLW","EALW","EARW","EALS"],
    relations: ["lover","friend","crush"],
    reason: "小众但不冷门，TA 背出门会被同温层秒认出来。" },
  { name: "家用陶艺手揉 DIY 材料包", searchQuery: "陶艺DIY材料包 软陶", priceMin: 16, priceMax: 40, priceTypical: 25, priceLabel: "¥16–40", emoji: "🏺",
    tags: ["DIY","新奇","动手","尝试","陶艺"],
    personas: ["EMLW","EALW","EARW","IALW"],
    relations: ["lover","friend","crush"],
    reason: "两个人窝在桌前捏一下午，比一束花更难忘。" },
  { name: "潮玩盲盒大礼包", searchQuery: "潮玩盲盒 礼盒", priceMin: 30, priceMax: 60, priceTypical: 40, priceLabel: "¥30–60", emoji: "🧸",
    tags: ["盲盒","收藏","治愈","摆件","可爱"],
    personas: ["EMRW","EALS","IALW","IMLW"],
    relations: ["lover","friend","colleague","crush"],
    reason: "拆盒的快乐 × 摆桌的快乐，TA 两样都不会放过。" },

  // ===== 体面/职场/轻奢 =====
  { name: "轻奢真皮卡包", searchQuery: "真皮卡包 轻奢", priceMin: 30, priceMax: 160, priceTypical: 80, priceLabel: "¥30–160", emoji: "👛",
    tags: ["皮具","职场","通勤","穿搭"],
    personas: ["EMRS","IMRS","EARS","IARS"],
    relations: ["lover","family","colleague"],
    reason: "出现在 TA 工位上的每一个物件，都是 TA 自我介绍的一部分。" },
  { name: "进口品牌钢笔", searchQuery: "钢笔 进口 商务礼盒", priceMin: 90, priceMax: 730, priceTypical: 290, priceLabel: "¥90–730", emoji: "🖋️",
    tags: ["书写","职场","签字","笔"],
    personas: ["EMRS","IMRS","IARS"],
    relations: ["lover","family","colleague"],
    reason: "一支会跟着 TA 签下很多重要时刻的笔。" },
  { name: "沙龙香水（小众款）", searchQuery: "沙龙香水 小众 礼盒", priceMin: 120, priceMax: 460, priceTypical: 200, priceLabel: "¥120–460", emoji: "🌸",
    tags: ["香水","香氛","气味","穿搭"],
    personas: ["EMRS","EALS","EARS","IALS"],
    relations: ["lover","crush","friend"],
    reason: "气味是 TA 留在房间里最低调的签名。" },

  // ===== 科技/极客 =====
  { name: "客制化机械键盘", searchQuery: "客制化机械键盘", priceMin: 300, priceMax: 500, priceTypical: 400, priceLabel: "¥300–500", emoji: "⌨️",
    tags: ["键盘","电脑","数码","机械","写代码","打字"],
    personas: ["EMRW","IMRW","IMRS"],
    relations: ["lover","friend","colleague"],
    reason: "每一次敲击都是 TA 给自己写的 BGM。" },
  { name: "降噪头戴耳机", searchQuery: "降噪头戴耳机", priceMin: 150, priceMax: 300, priceTypical: 220, priceLabel: "¥150–300", emoji: "🎧",
    tags: ["耳机","音乐","通勤","数码","降噪"],
    personas: ["IMRW","IMRS","IMLW","EMRW"],
    relations: ["lover","family","colleague","friend"],
    reason: "送 TA 一个能屏蔽世界、只留下喜欢之物的开关。" },
  { name: "创意桌面小风扇加湿器礼盒", searchQuery: "桌面小风扇 加湿器", priceMin: 29, priceMax: 50, priceTypical: 39, priceLabel: "¥29–50", emoji: "💨",
    tags: ["数码","科技","小家电","桌面"],
    personas: ["EMRW","IMRW","EARW"],
    relations: ["friend","colleague","family"],
    reason: "TA 桌面的下一个网红物件，提前帮 TA 拿下。" },

  // ===== 氛围/香薰/居家 =====
  { name: "手工大豆香薰蜡烛套装", searchQuery: "大豆蜡烛 香薰礼盒", priceMin: 70, priceMax: 140, priceTypical: 100, priceLabel: "¥70–140", emoji: "🕯️",
    tags: ["香薰","蜡烛","居家","氛围","治愈","睡眠"],
    personas: ["EALS","IALS","IMLS","IMLW","EARS"],
    relations: ["lover","friend","family","crush"],
    reason: "点上的那一刻，TA 的小宇宙就开机了。" },
  { name: "原创艺术家联名挂画", searchQuery: "艺术挂画 原创", priceMin: 200, priceMax: 600, priceTypical: 380, priceLabel: "¥200–600", emoji: "🖼️",
    tags: ["挂画","艺术","居家","设计","氛围"],
    personas: ["EALS","EALW","IALW","IARW"],
    relations: ["lover","friend","family"],
    reason: "TA 家空着的那面墙，等的就是这种作品。" },
  { name: "复古胶片相机", searchQuery: "胶片相机 复古", priceMin: 120, priceMax: 240, priceTypical: 180, priceLabel: "¥120–240", emoji: "📷",
    tags: ["相机","摄影","复古","记录","拍照"],
    personas: ["EALS","EALW","IMLW","IALW"],
    relations: ["lover","friend","crush"],
    reason: "TA 拍东西不为发朋友圈，只为以后某天能翻出来。" },

  // ===== 仪式感/定制 =====
  { name: "刻字银饰小项链", searchQuery: "刻字项链 银饰 定制", priceMin: 100, priceMax: 220, priceTypical: 160, priceLabel: "¥100–220", emoji: "📿",
    tags: ["首饰","项链","定制","刻字","仪式感"],
    personas: ["EARS","EALS","IALS","IMLS"],
    relations: ["lover","crush","family"],
    reason: "把一句只有你们懂的话，挂在 TA 锁骨之间。" },
  { name: "纪念日定制相册", searchQuery: "纪念日相册 定制", priceMin: 20, priceMax: 80, priceTypical: 32, priceLabel: "¥20–80", emoji: "📔",
    tags: ["相册","纪念日","定制","回忆","照片"],
    personas: ["EARS","IMLS","IALS","IMLW"],
    relations: ["lover","family","friend"],
    reason: "比起朋友圈，TA 更想被认真地翻看。" },
  { name: "高端原叶茶礼盒", searchQuery: "原叶茶 礼盒", priceMin: 160, priceMax: 300, priceTypical: 198, priceLabel: "¥160–300", emoji: "🍵",
    tags: ["茶","养生","送长辈","传统","居家"],
    personas: ["IARS","EARS","IALS","IMRS"],
    relations: ["family","colleague","lover"],
    reason: "得体、暖手、又给得出手，三件事一次完成。" },

  // ===== 温柔治愈/居家 =====
  { name: "毛绒抱枕 + 法兰绒毯套装", searchQuery: "抱枕毛毯套装 礼盒", priceMin: 30, priceMax: 80, priceTypical: 50, priceLabel: "¥30–80", emoji: "🛋️",
    tags: ["治愈","毛绒","居家","睡眠","保暖","软软的"],
    personas: ["IMLS","IALS","EALS","IMLW"],
    relations: ["lover","friend","family","crush"],
    reason: "TA 嘴上说不需要，钻进去之后绝对不会再起来。" },
  { name: "温感变色马克杯", searchQuery: "变色马克杯 礼物", priceMin: 20, priceMax: 50, priceTypical: 30, priceLabel: "¥20–50", emoji: "☕",
    tags: ["杯子","咖啡","茶","办公室","治愈","可爱"],
    personas: ["IMLS","EALS","IALS","IMLW","EMRS"],
    relations: ["colleague","friend","crush"],
    reason: "一杯热水的小心机，每天都能让 TA 笑一下。" },
  { name: "手写贺卡套组（一年份）", searchQuery: "贺卡套装 一年份", priceMin: 10, priceMax: 20, priceTypical: 15, priceLabel: "¥10–20", emoji: "💌",
    tags: ["贺卡","信","写字","心意","治愈"],
    personas: ["IMLS","EARS","IMLW","IALS"],
    relations: ["lover","friend","family","crush"],
    reason: "365 天里，你可以悄悄给 TA 留下很多个'惊喜下一秒'。" },

  // ===== 文艺/独处 =====
  { name: "独立出版杂志半年订阅", searchQuery: "独立杂志 订阅", priceMin: 150, priceMax: 420, priceTypical: 240, priceLabel: "¥150–420", emoji: "📰",
    tags: ["杂志","阅读","书","文艺","订阅"],
    personas: ["IMLW","EALW","IALW","IARW"],
    relations: ["lover","friend","colleague","crush"],
    reason: "每个月，TA 都会收到一次来自你的延迟惊喜。" },
  { name: "黑胶唱片入门套装", searchQuery: "黑胶唱片 入门", priceMin: 600, priceMax: 1500, priceTypical: 999, priceLabel: "¥600–1500", emoji: "💿",
    tags: ["黑胶","音乐","复古","收藏"],
    personas: ["IMLW","IALW","EALW","IARS"],
    relations: ["lover","friend","family"],
    reason: "TA 听音乐这件事，值得有一个专门的仪式。" },
  { name: "当当 / 京东读书电子礼品卡", searchQuery: "当当 京东读书 礼品卡", priceMin: 99, priceMax: 499, priceTypical: 199, priceLabel: "¥99–499", emoji: "📖",
    tags: ["书","阅读","书店","文艺"],
    personas: ["IMLW","IMRS","IALW","IARS","IALS"],
    relations: ["lover","friend","colleague","family","crush"],
    reason: "比起替 TA 选书，让 TA 自己挑半天，才是礼物。" },

  // ===== 极简/高效 =====
  { name: "MUJI 风桌面收纳一体站", searchQuery: "桌面收纳 一体 简约", priceMin: 20, priceMax: 90, priceTypical: 40, priceLabel: "¥20–90", emoji: "🗂️",
    tags: ["收纳","桌面","办公","极简","效率"],
    personas: ["IMRS","EMRS","IMRW"],
    relations: ["colleague","friend","family"],
    reason: "TA 喜欢把桌面整理成一张设计图，这件正合适。" },
  { name: "多口快充一体充电站", searchQuery: "多口充电站 快充", priceMin: 40, priceMax: 120, priceTypical: 80, priceLabel: "¥40–120", emoji: "🔌",
    tags: ["充电","数码","桌面","效率","通勤"],
    personas: ["IMRS","IMRW","EMRS","EMRW"],
    relations: ["lover","friend","family","colleague"],
    reason: "TA 桌上那一堆线，今天起退休。" },
  { name: "高品质基础款羊毛围巾", searchQuery: "羊毛围巾 基础款", priceMin: 100, priceMax: 180, priceTypical: 138, priceLabel: "¥100–180", emoji: "🧣",
    tags: ["围巾","保暖","穿搭","基础款","冬天"],
    personas: ["IMRS","EMRS","IARS","IMLS"],
    relations: ["lover","family","colleague"],
    reason: "颜色克制、剪裁讲究，TA 会戴很多年。" },

  // ===== 慢生活/家 =====
  { name: "桌面园艺小盆栽套装", searchQuery: "桌面盆栽 礼物", priceMin: 10, priceMax: 50, priceTypical: 20, priceLabel: "¥10–50", emoji: "🪴",
    tags: ["植物","园艺","治愈","居家","绿色"],
    personas: ["IALS","EALS","IMLS","IARS"],
    relations: ["friend","family","colleague","crush"],
    reason: "TA 喜欢照顾的东西，又多一个。" },
  { name: "手工陶瓷餐具一人份套组", searchQuery: "手工陶瓷餐具 一人份", priceMin: 50, priceMax: 190, priceTypical: 120, priceLabel: "¥50–190", emoji: "🍽️",
    tags: ["陶瓷","餐具","做饭","居家","美食"],
    personas: ["IALS","EALS","IARS","IMLS"],
    relations: ["lover","family","friend"],
    reason: "TA 一个人吃饭也想要好好吃饭。" },
  { name: "手冲咖啡入门套装", searchQuery: "手冲咖啡 入门套装", priceMin: 100, priceMax: 310, priceTypical: 160, priceLabel: "¥100–310", emoji: "☕",
    tags: ["咖啡","手冲","居家","早晨","治愈"],
    personas: ["IALS","EALW","IMRS","IMLW","EALS"],
    relations: ["lover","friend","family","colleague"],
    reason: "TA 的早晨，从此有了一段属于自己的 10 分钟。" },

  // ===== 二次元/游戏/赛博 =====
  { name: "Steam 数字礼品卡", searchQuery: "Steam 礼品卡", priceMin: 30, priceMax: 50, priceTypical: 40, priceLabel: "¥30–50", emoji: "🎮",
    tags: ["游戏","steam","数码","宅","虚拟"],
    personas: ["IALW","IMRW","EMRW","IARW"],
    relations: ["friend","lover","family","colleague","crush"],
    reason: "把选游戏的快乐和折扣季的心动都留给 TA。" },
  { name: "限量手办 / 周边盲盒", searchQuery: "限量手办 盲盒", priceMin: 70, priceMax: 130, priceTypical: 79, priceLabel: "¥70–130", emoji: "🗿",
    tags: ["手办","周边","二次元","收藏","盲盒"],
    personas: ["IALW","EMRW","IARW","IMLW"],
    relations: ["lover","friend","crush"],
    reason: "TA 的桌面博物馆，又多一件镇馆之宝。" },
  { name: "像素风 LED 桌面摆件", searchQuery: "像素 LED 桌面摆件", priceMin: 120, priceMax: 400, priceTypical: 159, priceLabel: "¥120–400", emoji: "🕹️",
    tags: ["桌面","摆件","像素","赛博","灯"],
    personas: ["IALW","EMRW","IARW"],
    relations: ["friend","colleague","crush","lover"],
    reason: "TA 桌面那点赛博气息，全靠这种小物件撑起来。" },

  // ===== 古典/传统 =====
  { name: "苏绣团扇礼盒", searchQuery: "苏绣团扇 礼盒", priceMin: 10, priceMax: 30, priceTypical: 20, priceLabel: "¥10–30", emoji: "🪭",
    tags: ["传统","手工","收藏","送长辈","古典"],
    personas: ["IARS","EARS","IALS","IMRS"],
    relations: ["family","lover","colleague"],
    reason: "TA 欣赏的是真正经得起时间放慢看的东西。" },
  { name: "古籍复刻精装本", searchQuery: "古籍复刻 精装", priceMin: 80, priceMax: 400, priceTypical: 180, priceLabel: "¥80–400", emoji: "📜",
    tags: ["书","古籍","收藏","文艺","传统"],
    personas: ["IARS","IMLW","IALS"],
    relations: ["family","friend","colleague"],
    reason: "TA 翻它的样子，本身就是一幅画。" },
  { name: "宜兴紫砂入门茶具", searchQuery: "紫砂茶具 入门", priceMin: 50, priceMax: 270, priceTypical: 165, priceLabel: "¥50–270", emoji: "🫖",
    tags: ["茶","紫砂","传统","居家","送长辈"],
    personas: ["IARS","EARS","IALS","IMRS"],
    relations: ["family","colleague","lover"],
    reason: "一套能用十年的东西，比一时的新奇更接近 TA 的口味。" },

  // ===== 神秘/小众/夜 =====
  { name: "塔罗牌精装礼盒", searchQuery: "塔罗牌 精装", priceMin: 80, priceMax: 180, priceTypical: 111, priceLabel: "¥80–180", emoji: "🔮",
    tags: ["塔罗","神秘","占卜","小众"],
    personas: ["IARW","IALW","IMLW","EALW"],
    relations: ["friend","crush","lover"],
    reason: "TA 不一定真信，但 TA 一定喜欢摊牌时的氛围感。" },
  { name: "天文望远镜入门款", searchQuery: "天文望远镜 入门", priceMin: 500, priceMax: 1200, priceTypical: 999, priceLabel: "¥500–1200", emoji: "🔭",
    tags: ["天文","星空","小众","户外","夜晚"],
    personas: ["IARW","IALW","EMRW","IMRW"],
    relations: ["lover","friend","family","crush"],
    reason: "下一次约 TA，不在咖啡馆而在天台。" },
  { name: "DIY 调香材料盒（精油 + 香基）", searchQuery: "DIY调香 精油材料包", priceMin: 15, priceMax: 60, priceTypical: 25, priceLabel: "¥15–60", emoji: "🌿",
    tags: ["香","实验","小众","DIY","气味"],
    personas: ["IARW","EALS","IALS","EALW"],
    relations: ["lover","friend","crush"],
    reason: "TA 喜欢的东西，从来不是货架上能直接找到的——亲手调一瓶。" },

  // ===== 万能补位（覆盖低预算/通用） =====
  { name: "精致手写感贺卡 + 鲜花单束", searchQuery: "鲜花贺卡 礼盒", priceMin: 10, priceMax: 40, priceTypical: 20, priceLabel: "¥10–40", emoji: "🌹",
    tags: ["鲜花","贺卡","治愈","心意"],
    personas: ["IMLS","EARS","EALS","IALS","IMLW"],
    relations: ["lover","crush","friend","family","colleague"],
    reason: "金额不大，但'你今天被人放在心上'这件事价值最大。" },
  { name: "联名设计师笔记本", searchQuery: "设计师 笔记本", priceMin: 20, priceMax: 60, priceTypical: 30, priceLabel: "¥20–60", emoji: "📓",
    tags: ["笔记本","书写","设计","文艺"],
    personas: ["IMLW","IMRS","EALW","IARS","EARS"],
    relations: ["friend","colleague","crush","lover"],
    reason: "TA 写下的下一段重要的事，希望发生在你送的本子里。" },
  { name: "星巴克实体礼品卡", searchQuery: "星巴克 实体礼品卡", priceMin: 95, priceMax: 195, priceTypical: 100, priceLabel: "¥95–195", emoji: "☕",
    tags: ["咖啡","下午茶","通勤","治愈"],
    personas: ["IMLS","IMRS","EMRS","IALS","IMLW","EALS"],
    relations: ["colleague","friend","crush"],
    reason: "得体、不越界、又能让 TA 想起你三五次。" },

  // ===== 100 元以下补充 =====
  { name: "手工香薰小蜡烛", searchQuery: "手工香薰蜡烛", priceMin: 60, priceMax: 160, priceTypical: 89, priceLabel: "¥60–160", emoji: "🕯️",
    tags: ["香薰","焦虑","助眠","治愈","居家"],
    personas: ["IMLS","IALS","IMLW","EALS","IARS"],
    relations: ["lover","friend","colleague","family","crush"],
    reason: "深夜点一枚，帮 TA 把一整天的紧绷轻轻化掉。" },
  { name: "云朵棉眼罩（热敷款）", searchQuery: "蒸汽眼罩 热敷", priceMin: 30, priceMax: 80, priceTypical: 50, priceLabel: "¥30–80", emoji: "😴",
    tags: ["助眠","眼罩","倒班","加班","治愈","劳累"],
    personas: ["IMLS","IMRS","IMLW","IALS","IARS"],
    relations: ["family","colleague","friend","lover"],
    reason: "TA 嘴上不说累，但你知道 TA 揉过眼睛到深夜几点。" },
  { name: "手冲单品咖啡豆 250g", searchQuery: "单品咖啡豆 250g", priceMin: 40, priceMax: 100, priceTypical: 55, priceLabel: "¥40–100", emoji: "☕",
    tags: ["咖啡","手冲","早餐","品质","生活"],
    personas: ["IMRS","EMRS","IMLW","IARS","EARS","IALS"],
    relations: ["colleague","friend","family","lover"],
    reason: "不是贵礼物，但 TA 每个早上都会谢你一次。" },
  { name: "口袋打卡小本 · 一年交换", searchQuery: "口袋本 交换日记", priceMin: 20, priceMax: 60, priceTypical: 35, priceLabel: "¥20–60", emoji: "📒",
    tags: ["记录","交换日记","仪式感","手写","文艺"],
    personas: ["IMLW","IMRS","EALS","IARS","EARS","IALS"],
    relations: ["lover","crush","friend","family"],
    reason: "送 TA 一整年都会拿出来用的东西，比一次性贵礼更走心。" },
  { name: "美术馆明信片套装（6 张）", searchQuery: "美术馆 明信片套装", priceMin: 10, priceMax: 70, priceTypical: 25, priceLabel: "¥10–70", emoji: "💌",
    tags: ["明信片","小众","文艺","小东西","走心"],
    personas: ["IMLW","IALW","EALW","IARW","EARS"],
    relations: ["crush","friend","lover"],
    reason: "金额轻、心意重，适合「还不太熟但想送点什么」的那一刻。" },
  { name: "治愈系梦幻夜灯", searchQuery: "治愈系夜灯 摆件", priceMin: 20, priceMax: 90, priceTypical: 50, priceLabel: "¥20–90", emoji: "💡",
    tags: ["夜灯","治愈","居家","可爱","摆件"],
    personas: ["IMLS","IMRW","IALS","IALW","EMRW"],
    relations: ["lover","friend","crush","family"],
    reason: "不是必需品，但 TA 每晚拍照都会提起你。" },
  { name: "轻奢香槟塔礼盒（含杯具）", searchQuery: "香槟塔 礼盒 杯具",
    priceMin: 18, priceMax: 49, priceTypical: 29, priceLabel: "¥18–49", emoji: "🍾",
    tags: ["香槟","派对","气氛","仪式"],
    personas: ["EMLS","EARS"],
    relations: ["friend","family","lover"],
    reason: "开场就把派对推上仪式感顶峰，TA 是天然主角。" },
  { name: "BOSE 便携派对蓝牙音响 SoundLink", searchQuery: "BOSE SoundLink 便携音箱",
    priceMin: 1000, priceMax: 1400, priceTypical: 1200, priceLabel: "¥1000–1400", emoji: "🔊",
    tags: ["音响","派对","数码","BOSE"],
    personas: ["EMLS","EMLW","EMRW"],
    relations: ["friend","colleague","lover"],
    reason: "TA 在哪开派对、BGM 就在哪——这是 TA 桌上的下一个常驻。" },
  { name: "威士忌入门精选三瓶套装", searchQuery: "威士忌 入门 三瓶 礼盒",
    priceMin: 69, priceMax: 200, priceTypical: 140, priceLabel: "¥69–200", emoji: "🥃",
    tags: ["酒","威士忌","收藏","品鉴"],
    personas: ["EMLS","EMRS","EARS"],
    relations: ["friend","family","colleague"],
    reason: "派对之后那杯酒，比派对本身更难忘。" },
  { name: "轻奢复古墨镜（设计师款）", searchQuery: "复古墨镜 设计师 轻奢",
    priceMin: 29, priceMax: 120, priceTypical: 69, priceLabel: "¥29–120", emoji: "🕶️",
    tags: ["墨镜","潮流","穿搭","设计师"],
    personas: ["EMLW","EMLS","EARW"],
    relations: ["friend","crush","lover"],
    reason: "TA 出门发的下一张街拍，靠这副镜框稳赢。" },
  { name: "GoPro / 大疆 Pocket 手持云台相机", searchQuery: "大疆 Pocket 3 云台相机",
    priceMin: 3500, priceMax: 4500, priceTypical: 3800, priceLabel: "¥3500–4500", emoji: "🎥",
    tags: ["相机","Vlog","数码","旅行"],
    personas: ["EMLW","EARW","EMRW"],
    relations: ["friend","lover","family"],
    reason: "TA 的下一段旅行，要从这台机器开始记录。" },
  { name: "潮牌联名球鞋（限量款）", searchQuery: "潮牌联名球鞋 限量",
    priceMin: 600, priceMax: 2500, priceTypical: 1200, priceLabel: "¥600–2500", emoji: "👟",
    tags: ["球鞋","潮流","限量","穿搭"],
    personas: ["EMLW","EARW","EMLS"],
    relations: ["friend","lover","crush"],
    reason: "穿上这双 TA 就赢了——你也跟着赢了。" },
  { name: "轻奢真皮公文包（设计师款）", searchQuery: "真皮公文包 设计师",
    priceMin: 300, priceMax: 750, priceTypical: 500, priceLabel: "¥300–750", emoji: "💼",
    tags: ["公文包","真皮","商务","通勤"],
    personas: ["EMRS","EARS","IMRS"],
    relations: ["family","colleague","lover"],
    reason: "TA 走进会议室的第一秒，就靠它定义气场。" },
  { name: "派克 / 万宝龙商务钢笔礼盒", searchQuery: "万宝龙 钢笔 礼盒",
    priceMin: 1200, priceMax: 6700, priceTypical: 3700, priceLabel: "¥1200–6700", emoji: "🖋️",
    tags: ["钢笔","商务","奢侈品","礼盒"],
    personas: ["EMRS","IARS","EARS"],
    relations: ["family","colleague","lover"],
    reason: "签字这件事，值得用一支让 TA 想顿一下的笔。" },
  { name: "高端机械腕表（精工 / 西铁城）", searchQuery: "精工机械表 男士",
    priceMin: 750, priceMax: 2400, priceTypical: 1600, priceLabel: "¥750–2400", emoji: "⌚",
    tags: ["手表","机械","商务","收藏"],
    personas: ["EMRS","IMRS","EARS"],
    relations: ["family","lover","colleague"],
    reason: "TA 抬手看时间的瞬间，TA 是 TA 自己。" },
  { name: "Switch OLED / PS5 数字版", searchQuery: "Switch OLED 主机",
    priceMin: 2000, priceMax: 2400, priceTypical: 2200, priceLabel: "¥2000–2400", emoji: "🎮",
    tags: ["游戏机","数码","收藏","Switch"],
    personas: ["EMRW","IMRW","EARW"],
    relations: ["lover","family","friend"],
    reason: "送 TA 一个真正属于 TA 的私人小宇宙。" },
  { name: "高端机械键盘（HHKB / 客制化）", searchQuery: "HHKB 静电容键盘",
    priceMin: 1500, priceMax: 2400, priceTypical: 2000, priceLabel: "¥1500–2400", emoji: "⌨️",
    tags: ["键盘","HHKB","数码","客制化"],
    personas: ["EMRW","IMRW","IMRS"],
    relations: ["colleague","lover","family"],
    reason: "TA 每天按下几千次的东西，值得最好的那一把。" },
  { name: "乐高大型收藏级套组（创意系列）", searchQuery: "乐高 创意系列 大型",
    priceMin: 2200, priceMax: 4000, priceTypical: 3200, priceLabel: "¥2200–4000", emoji: "🧱",
    tags: ["乐高","收藏","拼搭","成人"],
    personas: ["EMRW","EARW","IMRW"],
    relations: ["lover","family","friend"],
    reason: "周末两个人花 8 小时拼完，比一顿饭难忘。" },
  { name: "DIPTYQUE 香薰大蜡烛 300g", searchQuery: "DIPTYQUE 香薰蜡烛 300g",
    priceMin: 380, priceMax: 650, priceTypical: 550, priceLabel: "¥380–650", emoji: "🕯️",
    tags: ["香薰","蜡烛","DIPTYQUE","氛围"],
    personas: ["EALS","IALS","IARS"],
    relations: ["lover","friend","family"],
    reason: "TA 卧室那个味道，从这一盏开始定型。" },
  { name: "丹麦 Vipp / Stelton 设计感餐具套组", searchQuery: "Stelton 餐具 北欧",
    priceMin: 330, priceMax: 900, priceTypical: 650, priceLabel: "¥330–900", emoji: "🍽️",
    tags: ["餐具","设计","北欧","氛围"],
    personas: ["EALS","IARS","EARS"],
    relations: ["family","lover","colleague"],
    reason: "TA 准备一顿晚餐的仪式，从摆开它们开始。" },
  { name: "全屋香薰扩香器（智能款）", searchQuery: "智能扩香器 全屋",
    priceMin: 80, priceMax: 300, priceTypical: 150, priceLabel: "¥80–300", emoji: "🌫️",
    tags: ["扩香","智能","香薰","家居"],
    personas: ["EALS","IALS","EARS"],
    relations: ["lover","family","colleague"],
    reason: "推门进屋第一口气——TA 想起你。" },
  { name: "原创艺术家版画（限量签名）", searchQuery: "独立艺术家 版画",
    priceMin: 800, priceMax: 3000, priceTypical: 1900, priceLabel: "¥800–3000", emoji: "🖼️",
    tags: ["版画","艺术","限量","收藏"],
    personas: ["EALW","IALW","IARS","EALS"],
    relations: ["lover","family","friend"],
    channel: "offline", channelHint: "画廊 / 艺术家工作室",
    reason: "TA 家那面墙，等的就是这一幅。" },
  { name: "中画幅胶片相机入门款", searchQuery: "中画幅胶片相机 入门",
    priceMin: 420, priceMax: 2500, priceTypical: 900, priceLabel: "¥420–2500", emoji: "📷",
    tags: ["胶片","摄影","收藏","复古"],
    personas: ["EALW","IALW","EMRW"],
    relations: ["lover","friend","family"],
    reason: "TA 拍的下一组照片，会被冲洗店老板多看两眼。" },
  { name: "设计师联名手提皮包", searchQuery: "设计师 手提包 联名",
    priceMin: 39, priceMax: 240, priceTypical: 130, priceLabel: "¥39–240", emoji: "👜",
    tags: ["手提包","设计师","穿搭","联名"],
    personas: ["EALW","EMLW","EARS"],
    relations: ["lover","crush","friend"],
    reason: "出门一件，自带气场。" },
  { name: "高级订制蛋糕券（连锁烘焙）", searchQuery: "蛋糕券 高级 定制",
    priceMin: 130, priceMax: 270, priceTypical: 180, priceLabel: "¥130–270", emoji: "🎂",
    tags: ["蛋糕","生日","仪式","定制"],
    personas: ["EARS","EMLS","IMLS"],
    relations: ["family","lover","friend"],
    reason: "生日那天的仪式中心，从这一刀开始。" },
  { name: "轻奢首饰盒（旋转音乐款）", searchQuery: "音乐首饰盒 轻奢",
    priceMin: 39, priceMax: 200, priceTypical: 88, priceLabel: "¥39–200", emoji: "💍",
    tags: ["首饰盒","音乐盒","收纳","仪式"],
    personas: ["EARS","IARS","EALS"],
    relations: ["lover","family","crush"],
    reason: "打开它的瞬间，TA 会想起把它送给 TA 的那一天。" },
  { name: "高端节日花艺包月订阅（一季度）", searchQuery: "本地花艺包月",
    priceMin: 1000, priceMax: 2500, priceTypical: 1750, priceLabel: "¥1000–2500", emoji: "💐",
    tags: ["鲜花","订阅","仪式","治愈"],
    personas: ["EARS","EALS","IMLS"],
    relations: ["lover","family","crush"],
    channel: "offline", channelHint: "本地花艺工作室",
    reason: "每周一束花到 TA 家，把仪式拉成连续剧。" },
  { name: "Mini 大疆无人机 / 入门航拍", searchQuery: "大疆 Mini 4 无人机",
    priceMin: 2100, priceMax: 4800, priceTypical: 2400, priceLabel: "¥2100–4800", emoji: "🚁",
    tags: ["无人机","数码","航拍","户外"],
    personas: ["EARW","EMLW","EMRW"],
    relations: ["friend","lover","family"],
    reason: "TA 的下一次旅行，要从天上拍起。" },
  { name: "VR 游戏头显（Quest 3）", searchQuery: "Quest 3 VR 头显",
    priceMin: 3200, priceMax: 3700, priceTypical: 3400, priceLabel: "¥3200–3700", emoji: "🕶️",
    tags: ["VR","游戏","数码","沉浸"],
    personas: ["EARW","EMRW","IMRW"],
    relations: ["lover","family","friend"],
    reason: "TA 在家就能去另一个世界——这是当下最好的逃离。" },
  { name: "高端入门级电吉他套装", searchQuery: "电吉他 入门套装 Fender",
    priceMin: 1200, priceMax: 2500, priceTypical: 1700, priceLabel: "¥1200–2500", emoji: "🎸",
    tags: ["乐器","吉他","音乐","入门"],
    personas: ["EARW","EALW","IALW"],
    relations: ["lover","family","friend"],
    reason: "TA 心里藏着一首没弹出来的歌。" },
  { name: "乳胶记忆枕（高端进口款）", searchQuery: "泰国乳胶枕 高端",
    priceMin: 300, priceMax: 550, priceTypical: 400, priceLabel: "¥300–550", emoji: "🛌",
    tags: ["枕头","睡眠","治愈","进口"],
    personas: ["IMLS","IALS","IMRS"],
    relations: ["lover","family","colleague"],
    reason: "TA 每一晚的休息，值得最好的承托。" },
  { name: "养生中药足浴礼盒（半年装）", searchQuery: "中药足浴 礼盒 半年",
    priceMin: 29, priceMax: 99, priceTypical: 59, priceLabel: "¥29–99", emoji: "🦶",
    tags: ["足浴","养生","治愈","中药"],
    personas: ["IMLS","IALS","IARS"],
    relations: ["family","colleague","lover"],
    reason: "长辈/疲惫的 TA 每晚最期待的 20 分钟。" },
  { name: "加湿暖灯一体助眠器", searchQuery: "助眠 暖灯 加湿器",
    priceMin: 39, priceMax: 180, priceTypical: 89, priceLabel: "¥39–180", emoji: "🌙",
    tags: ["助眠","加湿","暖光","治愈"],
    personas: ["IMLS","IALS","IMRS"],
    relations: ["lover","family","colleague"],
    reason: "卧室灯一关，整个房间就软了下来。" },
  { name: "高端绒毯（北欧设计款）", searchQuery: "羊毛毯 北欧 高端",
    priceMin: 150, priceMax: 800, priceTypical: 400, priceLabel: "¥150–800", emoji: "🧶",
    tags: ["毯子","羊毛","治愈","家居"],
    personas: ["IMLS","IALS","IARS"],
    relations: ["lover","family","colleague"],
    reason: "裹着它窝沙发的下午，TA 想起你三五次。" },
  { name: "乳胶记忆护颈靠垫（办公室款）", searchQuery: "颈椎枕 办公 乳胶",
    priceMin: 23, priceMax: 160, priceTypical: 49, priceLabel: "¥23–160", emoji: "💆",
    tags: ["颈椎","办公","健康","治愈"],
    personas: ["IMLS","IMRS","IALS"],
    relations: ["colleague","family","lover"],
    reason: "TA 在工位坐 10 小时，这是少有的实质性关心。" },
  { name: "Kindle Oasis / 文石电子阅读器", searchQuery: "Kindle 电子阅读器",
    priceMin: 700, priceMax: 1800, priceTypical: 1100, priceLabel: "¥700–1800", emoji: "📕",
    tags: ["阅读","Kindle","电子书","数码"],
    personas: ["IMLW","IMRS","IARS"],
    relations: ["lover","family","friend"],
    reason: "装得下 TA 一辈子读不完的书。" },
  { name: "高端日记本（皮面手账礼盒）", searchQuery: "皮面日记本 手账 礼盒",
    priceMin: 18, priceMax: 120, priceTypical: 39, priceLabel: "¥18–120", emoji: "📓",
    tags: ["日记","手账","皮面","收藏"],
    personas: ["IMLW","IARS","EARS"],
    relations: ["lover","family","colleague"],
    reason: "TA 写下的下一段重要的事，会发生在你送的这本里。" },
  { name: "作家签名版精装书套组（3 本）", searchQuery: "作家签名版 书市",
    priceMin: 500, priceMax: 1200, priceTypical: 850, priceLabel: "¥500–1200", emoji: "📚",
    tags: ["书","签名","精装","收藏"],
    personas: ["IMLW","IARS","IALW"],
    relations: ["lover","family","friend"],
    channel: "offline", channelHint: "书店签售会 / 官方店",
    reason: "书架最显眼那格，从今天起属于这套。" },
  { name: "iPad Mini / 入门 iPad", searchQuery: "iPad Mini",
    priceMin: 3300, priceMax: 4100, priceTypical: 4000, priceLabel: "¥3300–4100", emoji: "📲",
    tags: ["iPad","数码","效率","苹果"],
    personas: ["IMRS","IMRW","EMRS"],
    relations: ["colleague","family","lover"],
    reason: "TA 的下一台日常设备，比手机大、比电脑轻。" },
  { name: "高端无线降噪耳机（Sony WH-1000XM）", searchQuery: "Sony WH-1000XM5",
    priceMin: 1800, priceMax: 2300, priceTypical: 2200, priceLabel: "¥1800–2300", emoji: "🎧",
    tags: ["耳机","降噪","Sony","通勤"],
    personas: ["IMRS","IMRW","IMLW"],
    relations: ["colleague","lover","family"],
    reason: "送 TA 一个能屏蔽世界的开关。" },
  { name: "轻薄电脑包 + 配件全套（极简款）", searchQuery: "电脑包 极简 真皮",
    priceMin: 170, priceMax: 500, priceTypical: 300, priceLabel: "¥170–500", emoji: "💻",
    tags: ["电脑包","极简","通勤","商务"],
    personas: ["IMRS","EMRS","IARS"],
    relations: ["colleague","family","lover"],
    reason: "通勤路上的全部家当，被一只包稳稳收住。" },
  { name: "高端 NAS 网络存储入门款", searchQuery: "群晖 NAS 入门",
    priceMin: 1400, priceMax: 2900, priceTypical: 2300, priceLabel: "¥1400–2900", emoji: "💾",
    tags: ["NAS","数码","存储","极客"],
    personas: ["IMRW","EARW"],
    relations: ["family","colleague","lover"],
    reason: "TA 终于有一个地方，能放下所有想留下的文件。" },
  { name: "机械键盘客制化整套（轴+键帽）", searchQuery: "机械键盘 客制化 整套",
    priceMin: 98, priceMax: 400, priceTypical: 220, priceLabel: "¥98–400", emoji: "⌨️",
    tags: ["键盘","客制化","数码","极客"],
    personas: ["IMRW","EMRW","IMRS"],
    relations: ["lover","colleague","friend"],
    reason: "TA 桌上唯一一件、TA 愿意花一整夜调试的东西。" },
  { name: "曲面带鱼屏显示器", searchQuery: "带鱼屏 曲面显示器",
    priceMin: 900, priceMax: 2000, priceTypical: 1600, priceLabel: "¥900–2000", emoji: "🖥️",
    tags: ["显示器","曲面","数码","效率"],
    personas: ["IMRW","IMRS","EMRS"],
    relations: ["lover","family","colleague"],
    reason: "TA 工位那块屏，决定 TA 每天的心情。" },
  { name: "户外露营折叠桌椅套装", searchQuery: "露营桌椅 套装 折叠",
    priceMin: 38, priceMax: 81, priceTypical: 50, priceLabel: "¥38–81", emoji: "🏕️",
    tags: ["露营","户外","桌椅","慢生活"],
    personas: ["IALS","EALW","EARW"],
    relations: ["family","lover","friend"],
    reason: "TA 下一个周末，从打开它开始。" },
  { name: "高端电热水壶 + 茶具一体台", searchQuery: "煮茶器 电热 茶具",
    priceMin: 98, priceMax: 270, priceTypical: 130, priceLabel: "¥98–270", emoji: "🫖",
    tags: ["茶具","煮茶","养生","慢生活"],
    personas: ["IALS","IARS","IMLS"],
    relations: ["family","colleague","lover"],
    reason: "TA 的下午时光，从一壶咕嘟咕嘟开始。" },
  { name: "手工榆木餐桌方凳（北欧风）", searchQuery: "实木方凳 北欧 手工",
    priceMin: 19, priceMax: 38, priceTypical: 25, priceLabel: "¥19–38", emoji: "🪑",
    tags: ["家具","木质","北欧","家居"],
    personas: ["IALS","IARS","EALS"],
    relations: ["family","lover","colleague"],
    reason: "乔迁那天进门最先坐下来的，是这一把。" },
  { name: "高端瑜伽垫 + 辅具全套", searchQuery: "瑜伽垫 高端 辅具",
    priceMin: 27, priceMax: 160, priceTypical: 52, priceLabel: "¥27–160", emoji: "🧘",
    tags: ["瑜伽","运动","健康","慢生活"],
    personas: ["IALS","IMLS","IMRS"],
    relations: ["lover","family","colleague"],
    reason: "TA 每天早起的 30 分钟，从展开它开始。" },
  { name: "户外咖啡冲煮便携套装", searchQuery: "户外咖啡 便携套装",
    priceMin: 100, priceMax: 400, priceTypical: 200, priceLabel: "¥100–400", emoji: "☕",
    tags: ["咖啡","户外","便携","慢生活"],
    personas: ["IALS","EALW","IARW"],
    relations: ["lover","family","friend"],
    reason: "山上煮的那杯比城里更香——你帮 TA 准备好了。" },
  { name: "全画幅微单入门套机", searchQuery: "全画幅微单 入门",
    priceMin: 8100, priceMax: 9300, priceTypical: 9000, priceLabel: "¥8100–9300", emoji: "📸",
    tags: ["相机","微单","摄影","数码"],
    personas: ["IALW","EALW","EMRW"],
    relations: ["lover","family","friend"],
    reason: "TA 想拍的那个世界，配得上一台真正的相机。" },
  { name: "高端电子合成器入门款", searchQuery: "合成器 电子 入门",
    priceMin: 800, priceMax: 2500, priceTypical: 1500, priceLabel: "¥800–2500", emoji: "🎹",
    tags: ["合成器","音乐","数码","创作"],
    personas: ["IALW","EARW","IMRW"],
    relations: ["lover","friend","family"],
    reason: "TA 脑子里那段旋律，今天可以做出来。" },
  { name: "宜兴顶级紫砂壶（名家款）", searchQuery: "紫砂壶 名家 宜兴",
    priceMin: 300, priceMax: 1500, priceTypical: 600, priceLabel: "¥300–1500", emoji: "🫖",
    tags: ["紫砂","茶具","收藏","古典"],
    personas: ["IARS","IALS","EMRS"],
    relations: ["family","colleague","lover"],
    reason: "TA 喝茶这件事，从此有了一只值得养十年的器物。" },
  { name: "古琴 / 箫入门礼盒", searchQuery: "古琴 入门 礼盒",
    priceMin: 78, priceMax: 500, priceTypical: 300, priceLabel: "¥78–500", emoji: "🎶",
    tags: ["古琴","乐器","传统","收藏"],
    personas: ["IARS","IALW","IARW"],
    relations: ["lover","family","friend"],
    reason: "TA 心里那段没听过的曲，等的就是 TA 自己抚出来。" },
  { name: "全手工苏绣艺术摆件", searchQuery: "苏绣 摆件 手工",
    priceMin: 140, priceMax: 360, priceTypical: 220, priceLabel: "¥140–360", emoji: "🪡",
    tags: ["苏绣","手工","摆件","传统"],
    personas: ["IARS","EARS","EALS"],
    relations: ["family","lover","colleague"],
    reason: "TA 客厅那块墙面，从这一幅开始有故事。" },
  { name: "专业天文望远镜（中级入门）", searchQuery: "天文望远镜 中级",
    priceMin: 700, priceMax: 4400, priceTypical: 1200, priceLabel: "¥700–4400", emoji: "🔭",
    tags: ["天文","望远镜","观星","小众"],
    personas: ["IARW","IALW","IMRW"],
    relations: ["lover","family","friend"],
    reason: "TA 一直想看清楚的那颗星，今晚就能看清。" },
  { name: "高端塔罗 / 占星精装套盒（限量版）", searchQuery: "塔罗牌 限量 精装",
    priceMin: 99, priceMax: 320, priceTypical: 140, priceLabel: "¥99–320", emoji: "🔮",
    tags: ["塔罗","占星","限量","小众"],
    personas: ["IARW","IALW","EALW"],
    relations: ["lover","friend","crush"],
    reason: "TA 解读世界的那套工具，值得最美的一副。" },
  { name: "高端晶体矿石原石收藏套装", searchQuery: "水晶原石 收藏 礼盒",
    priceMin: 25, priceMax: 190, priceTypical: 40, priceLabel: "¥25–190", emoji: "💎",
    tags: ["矿石","水晶","收藏","神秘"],
    personas: ["IARW","IARS","IALW"],
    relations: ["lover","family","friend"],
    reason: "TA 桌上压着的那块石头，从此有了故事。" },
  { name: "派对一次性氛围灯套装", searchQuery: "派对氛围灯 套装",
    priceMin: 12, priceMax: 49, priceTypical: 20, priceLabel: "¥12–49", emoji: "🪩",
    tags: ["派对","灯光","氛围","布置"],
    personas: ["EMLS","EARS"],
    relations: ["friend","colleague","family"],
    reason: "开 5 分钟就能让客厅变 club。" },
  { name: "派对游戏小卡套装（成人版）", searchQuery: "派对游戏 卡牌 成人",
    priceMin: 12, priceMax: 25, priceTypical: 18, priceLabel: "¥12–25", emoji: "🃏",
    tags: ["派对","游戏","社交","卡牌"],
    personas: ["EMLS","EMLW","EARW"],
    relations: ["friend","colleague","crush"],
    reason: "破冰最快的一副牌，每个朋友都欠 TA 一次输。" },
  { name: "调酒师入门工具套装", searchQuery: "调酒工具 入门",
    priceMin: 14, priceMax: 49, priceTypical: 29, priceLabel: "¥14–49", emoji: "🍸",
    tags: ["调酒","派对","入门","工具"],
    personas: ["EMLS","EARS","EMRW"],
    relations: ["friend","lover","family"],
    reason: "TA 下一场派对的主理人位置，从这套工具开始。" },
  { name: "专业派对纸杯 + 一次性餐具礼盒", searchQuery: "派对一次性餐具 礼盒",
    priceMin: 6, priceMax: 26, priceTypical: 12, priceLabel: "¥6–26", emoji: "🥤",
    tags: ["派对","餐具","布置","氛围"],
    personas: ["EMLS","EARS"],
    relations: ["friend","family","colleague"],
    reason: "派对收拾这件事，TA 早就放弃自己动手了。" },
  { name: "卡拉 OK 蓝牙麦克风（家用）", searchQuery: "家用麦克风 蓝牙 卡拉ok",
    priceMin: 39, priceMax: 300, priceTypical: 160, priceLabel: "¥39–300", emoji: "🎤",
    tags: ["麦克风","卡拉OK","派对","蓝牙"],
    personas: ["EMLS","EMLW","EARW"],
    relations: ["friend","family","colleague"],
    reason: "客厅瞬间变包房——周末就在 TA 家。" },
  { name: "自制鸡尾酒原料礼盒", searchQuery: "鸡尾酒 原料 礼盒",
    priceMin: 49, priceMax: 140, priceTypical: 82, priceLabel: "¥49–140", emoji: "🍹",
    tags: ["鸡尾酒","派对","DIY","酒"],
    personas: ["EMLS","EARS","EALS"],
    relations: ["friend","lover","family"],
    reason: "TA 永远是朋友群里第一个张罗喝什么的那个。" },
  { name: "瑞士军刀 / 工具卡随身款", searchQuery: "瑞士军刀 多功能",
    priceMin: 80, priceMax: 300, priceTypical: 150, priceLabel: "¥80–300", emoji: "🔧",
    tags: ["工具","随身","实用","户外"],
    personas: ["EMLS","EARW","EMRS"],
    relations: ["friend","family","colleague"],
    reason: "TA 出门朋友总要找的那一个能解决问题的人。" },
  { name: "潮牌联名 T 恤（限定款）", searchQuery: "潮牌联名 T恤 限定",
    priceMin: 59, priceMax: 300, priceTypical: 120, priceLabel: "¥59–300", emoji: "👕",
    tags: ["T恤","潮牌","限定","穿搭"],
    personas: ["EMLW","EMLS","EALW"],
    relations: ["friend","lover","crush"],
    reason: "TA 衣柜里下一件被穿出门的那一件。" },
  { name: "潮玩 LABUBU / POPMART 大盒", searchQuery: "LABUBU 大盒 潮玩",
    priceMin: 69, priceMax: 120, priceTypical: 98, priceLabel: "¥69–120", emoji: "🧸",
    tags: ["潮玩","盲盒","收藏","可爱"],
    personas: ["EMLW","EMRW","EALS"],
    relations: ["friend","lover","crush"],
    reason: "TA 桌上那个会被同事一直问的玩偶。" },
  { name: "潮流复古帽子（设计师款）", searchQuery: "复古帽子 设计师",
    priceMin: 40, priceMax: 90, priceTypical: 60, priceLabel: "¥40–90", emoji: "🧢",
    tags: ["帽子","潮流","穿搭","复古"],
    personas: ["EMLW","EALW","EMLS"],
    relations: ["friend","crush","lover"],
    reason: "出门 30 秒，整套穿搭瞬间完整。" },
  { name: "街头风金属链条挂饰", searchQuery: "金属链条 挂饰 街头",
    priceMin: 6, priceMax: 20, priceTypical: 13, priceLabel: "¥6–20", emoji: "⛓️",
    tags: ["首饰","街头","穿搭","金属"],
    personas: ["EMLW","EARW"],
    relations: ["lover","crush","friend"],
    reason: "TA 的本命搭配，离不开这条链子。" },
  { name: "潮流滑板 / 长板入门", searchQuery: "滑板 长板 入门",
    priceMin: 200, priceMax: 700, priceTypical: 600, priceLabel: "¥200–700", emoji: "🛹",
    tags: ["滑板","运动","潮流","户外"],
    personas: ["EMLW","EARW","EMLS"],
    relations: ["lover","friend","crush"],
    reason: "TA 周末从家门口踩到河边——这是 TA 想要的那种自由。" },
  { name: "3D 打印潮流摆件", searchQuery: "3D打印 摆件 潮流",
    priceMin: 40, priceMax: 150, priceTypical: 80, priceLabel: "¥40–150", emoji: "🗿",
    tags: ["3D打印","摆件","潮玩","设计"],
    personas: ["EMLW","EMRW","IMRW"],
    relations: ["friend","colleague","lover"],
    reason: "TA 工位上最近的话题中心，就长这样。" },
  { name: "街头潮流贴纸大全套", searchQuery: "潮牌贴纸 套装",
    priceMin: 6, priceMax: 20, priceTypical: 13, priceLabel: "¥6–20", emoji: "🏷️",
    tags: ["贴纸","潮流","收藏","DIY"],
    personas: ["EMLW","EARW"],
    relations: ["friend","crush","colleague"],
    reason: "贴满 TA 的电脑、行李箱、滑板——把 TA 风格印在每件物件上。" },
  { name: "VR 入门头显（PICO）", searchQuery: "PICO 4 VR",
    priceMin: 1500, priceMax: 2500, priceTypical: 2000, priceLabel: "¥1500–2500", emoji: "🕹️",
    tags: ["VR","游戏","数码","沉浸"],
    personas: ["EARW","EMRW","IMRW"],
    relations: ["lover","friend","family"],
    reason: "在家就能去另一个国家——给 TA 一个新门票。" },
  { name: "剧本杀实体本套装", searchQuery: "剧本杀 实体本",
    priceMin: 20, priceMax: 58, priceTypical: 40, priceLabel: "¥20–58", emoji: "🃏",
    tags: ["剧本杀","游戏","社交","收藏"],
    personas: ["EARW","EMLW","EMLS"],
    relations: ["friend","colleague","lover"],
    reason: "周末聚会的脚本，TA 早就想攒一柜子了。" },
  { name: "立体投影互动小游戏机", searchQuery: "投影互动 小游戏机",
    priceMin: 200, priceMax: 500, priceTypical: 200, priceLabel: "¥200–500", emoji: "🎯",
    tags: ["游戏","互动","投影","派对"],
    personas: ["EARW","EMLW","EARS"],
    relations: ["family","friend","lover"],
    reason: "客厅瞬间变成一家小型游乐场。" },
  { name: "复古游戏机迷你版（FC / 街机）", searchQuery: "FC 迷你 复古游戏",
    priceMin: 30, priceMax: 140, priceTypical: 99, priceLabel: "¥30–140", emoji: "🎮",
    tags: ["复古","游戏","收藏","怀旧"],
    personas: ["EARW","IMRW","EMRW"],
    relations: ["lover","friend","family"],
    reason: "小学放学回家那种快乐，TA 没忘。" },
  { name: "密室逃脱主题双人券", searchQuery: "密室逃脱 主题馆",
    priceMin: 150, priceMax: 400, priceTypical: 275, priceLabel: "¥150–400", emoji: "🗝️",
    tags: ["密室","体验","双人","新奇"],
    personas: ["EARW","EMLW","EARS"],
    relations: ["lover","friend","crush"],
    channel: "offline", channelHint: "大众点评 / 门店预约",
    reason: "约会的下一种打开方式，比电影刺激十倍。" },
  { name: "卡牌游戏珍藏（万智牌 / 游戏王）", searchQuery: "万智牌 珍藏 卡牌",
    priceMin: 200, priceMax: 800, priceTypical: 400, priceLabel: "¥200–800", emoji: "🃏",
    tags: ["卡牌","游戏","收藏","策略"],
    personas: ["EARW","EMRW","IMRW"],
    relations: ["friend","lover","family"],
    reason: "TA 的策略游戏世界，从这一盒打开。" },
  { name: "乐高大型机械组（旗舰款）", searchQuery: "乐高 机械组 旗舰",
    priceMin: 2000, priceMax: 3800, priceTypical: 2400, priceLabel: "¥2000–3800", emoji: "🧱",
    tags: ["乐高","机械","收藏","拼搭"],
    personas: ["EARW","EMRW","IMRW"],
    relations: ["lover","family","friend"],
    reason: "TA 桌上摆三年都不嫌烦的那一件。" },
  { name: "猫窝 / 狗窝（宠物治愈款）", searchQuery: "猫窝 宠物 治愈",
    priceMin: 20, priceMax: 140, priceTypical: 37, priceLabel: "¥20–140", emoji: "🐱",
    tags: ["宠物","治愈","家居","柔软"],
    personas: ["IMLS","IALS"],
    relations: ["family","lover","friend"],
    reason: "TA 家的小毛茸茸，配得上更软的一块地。" },
  { name: "高端中药养生礼盒（阿胶/燕窝）", searchQuery: "阿胶 燕窝 礼盒",
    priceMin: 99, priceMax: 200, priceTypical: 160, priceLabel: "¥99–200", emoji: "🌿",
    tags: ["养生","中药","礼盒","治愈"],
    personas: ["IMLS","IARS"],
    relations: ["family","colleague","lover"],
    reason: "长辈最受用、TA 也不舍得自己买的那一种。" },
  { name: "温暖系羊毛披肩（家居款）", searchQuery: "羊毛披肩 家居",
    priceMin: 68, priceMax: 200, priceTypical: 130, priceLabel: "¥68–200", emoji: "🧣",
    tags: ["羊毛","披肩","治愈","家居"],
    personas: ["IMLS","IALS","IARS"],
    relations: ["family","lover","colleague"],
    reason: "TA 沙发上的标准动作：缩在它里面看一下午。" },
  { name: "夜间助眠香薰精油套装", searchQuery: "助眠 精油 套装",
    priceMin: 30, priceMax: 70, priceTypical: 49, priceLabel: "¥30–70", emoji: "😴",
    tags: ["精油","助眠","治愈","香薰"],
    personas: ["IMLS","IALS","EALS"],
    relations: ["lover","family","colleague"],
    reason: "TA 睡前那 5 分钟，从一滴薰衣草开始安静下来。" },
  { name: "加热颈椎按摩仪", searchQuery: "颈椎按摩仪 加热",
    priceMin: 99, priceMax: 600, priceTypical: 300, priceLabel: "¥99–600", emoji: "💆",
    tags: ["按摩","颈椎","健康","治愈"],
    personas: ["IMLS","IMRS","EMRS"],
    relations: ["family","colleague","lover"],
    reason: "TA 加班完最想要的下一个动作。" },
  { name: "治愈系毛绒玩偶大号", searchQuery: "毛绒玩偶 大号 治愈",
    priceMin: 38, priceMax: 88, priceTypical: 58, priceLabel: "¥38–88", emoji: "🧸",
    tags: ["毛绒","治愈","可爱","拥抱"],
    personas: ["IMLS","EALS","IALS"],
    relations: ["lover","family","crush"],
    reason: "一抱进怀里就被治愈的那种大小。" },
  { name: "高端无糖养生茶礼盒（一年装）", searchQuery: "养生茶 一年 礼盒",
    priceMin: 190, priceMax: 400, priceTypical: 300, priceLabel: "¥190–400", emoji: "🍵",
    tags: ["茶","养生","礼盒","治愈"],
    personas: ["IMLS","IARS","IALS"],
    relations: ["family","colleague","lover"],
    reason: "长辈每天最期待的一杯，安静热气腾。" },
  { name: "高级定制纪念日相册（手工烫金）", searchQuery: "手工烫金 相册 定制",
    priceMin: 28, priceMax: 200, priceTypical: 70, priceLabel: "¥28–200", emoji: "📔",
    tags: ["相册","定制","纪念","仪式"],
    personas: ["EARS","EALS","IMLW"],
    relations: ["lover","family","friend"],
    reason: "一本翻 10 年还不旧的纪念。" },
  { name: "全套节日布置礼盒（圣诞/春节）", searchQuery: "圣诞 布置 礼盒",
    priceMin: 60, priceMax: 300, priceTypical: 150, priceLabel: "¥60–300", emoji: "🎄",
    tags: ["节日","布置","仪式","氛围"],
    personas: ["EARS","EALS","EMLS"],
    relations: ["family","lover","colleague"],
    reason: "TA 家门口的节日感，从这一箱开始展开。" },
  { name: "DIY 婚戒木匣 / 戒指收纳定制", searchQuery: "手工木工作室 戒指盒",
    priceMin: 100, priceMax: 400, priceTypical: 250, priceLabel: "¥100–400", emoji: "💍",
    tags: ["戒指盒","定制","木质","仪式"],
    personas: ["EARS","IARS","EALS"],
    relations: ["lover","family","crush"],
    channel: "offline", channelHint: "本地手工工作室",
    reason: "TA 的那只戒指，从此有了一个像家的地方。" },
  { name: "高级蛋糕模具 + 烘焙工具套装", searchQuery: "烘焙工具 蛋糕 套装",
    priceMin: 30, priceMax: 86, priceTypical: 60, priceLabel: "¥30–86", emoji: "🧁",
    tags: ["烘焙","蛋糕","DIY","仪式"],
    personas: ["EARS","EALS","IMLS"],
    relations: ["lover","family","friend"],
    reason: "TA 给朋友做生日蛋糕的那一年，从这盒开始。" },
  { name: "摄影师约拍纪念套餐券", searchQuery: "摄影约拍 工作室",
    priceMin: 500, priceMax: 1200, priceTypical: 850, priceLabel: "¥500–1200", emoji: "📷",
    tags: ["摄影","纪念","定制","仪式"],
    personas: ["EARS","EALW","EMLW"],
    relations: ["lover","family","friend"],
    channel: "offline", channelHint: "大众点评 / 小红书",
    reason: "今年这个日子，存下来值得回看 10 年。" },
  { name: "高级烫金请柬礼盒（空白可定制）", searchQuery: "烫金请柬 礼盒",
    priceMin: 30, priceMax: 200, priceTypical: 80, priceLabel: "¥30–200", emoji: "💌",
    tags: ["请柬","定制","仪式","烫金"],
    personas: ["EARS","IARS"],
    relations: ["lover","family","colleague"],
    reason: "乔迁、婚礼、生日，TA 早就想换一套体面的。" },
  { name: "个性定制丝巾礼盒", searchQuery: "定制丝巾 礼盒",
    priceMin: 99, priceMax: 300, priceTypical: 200, priceLabel: "¥99–300", emoji: "🧣",
    tags: ["丝巾","定制","穿搭","礼盒"],
    personas: ["EARS","EALS","IARS"],
    relations: ["family","lover","colleague"],
    reason: "长辈拿出门最得体的那一件，从你开始。" },
  { name: "高端单丛 / 凤凰茶礼盒", searchQuery: "凤凰单丛 茶 礼盒",
    priceMin: 120, priceMax: 400, priceTypical: 200, priceLabel: "¥120–400", emoji: "🍵",
    tags: ["茶","商务","礼盒","得体"],
    personas: ["IARS","IMRS","EMRS","IALS"],
    relations: ["colleague","family"],
    reason: "得体、不轻浮，TA 收下时心里点过头。" },
  { name: "轻奢办公桌摆件（金属雕塑）", searchQuery: "办公桌摆件 金属 设计",
    priceMin: 49, priceMax: 170, priceTypical: 98, priceLabel: "¥49–170", emoji: "🗿",
    tags: ["摆件","办公","设计","桌面"],
    personas: ["EMRS","IMRS","EARS"],
    relations: ["colleague","family"],
    reason: "TA 工位上唯一让会议室扫过来时停一秒的那件。" },
  { name: "商务会议杯（保温陶瓷）", searchQuery: "商务保温杯 陶瓷",
    priceMin: 39, priceMax: 170, priceTypical: 99, priceLabel: "¥39–170", emoji: "🥤",
    tags: ["保温杯","商务","办公","通勤"],
    personas: ["EMRS","IMRS","EARS"],
    relations: ["colleague","family"],
    reason: "TA 每天 9 点 5 分钟出现在工位上的那只杯。" },
  { name: "商务名片夹（真皮款）", searchQuery: "真皮名片夹 商务",
    priceMin: 25, priceMax: 69, priceTypical: 49, priceLabel: "¥25–69", emoji: "💳",
    tags: ["名片夹","真皮","商务","得体"],
    personas: ["EMRS","IMRS","EARS"],
    relations: ["colleague","family"],
    reason: "递出名片的那个动作，从此多一秒分量。" },
  { name: "独立精装办公手账礼盒", searchQuery: "商务 手账 礼盒",
    priceMin: 5, priceMax: 16, priceTypical: 9, priceLabel: "¥5–16", emoji: "📓",
    tags: ["手账","办公","商务","得体"],
    personas: ["EMRS","IMRS","IMLW"],
    relations: ["colleague","family"],
    reason: "开会时翻开就懂的那种人，从这本开始。" },
  { name: "商务护肤套组（男女通用）", searchQuery: "商务护肤 男女 套盒",
    priceMin: 88, priceMax: 600, priceTypical: 260, priceLabel: "¥88–600", emoji: "🧴",
    tags: ["护肤","商务","得体","通勤"],
    personas: ["EMRS","EARS","IMRS"],
    relations: ["colleague","family"],
    reason: "工作那么累，至少脸的状态不能塌。" },
  { name: "轻奢茶包礼盒（节日通用）", searchQuery: "茶包 礼盒 商务",
    priceMin: 69, priceMax: 130, priceTypical: 89, priceLabel: "¥69–130", emoji: "🍃",
    tags: ["茶包","礼盒","节日","商务"],
    personas: ["IMRS","EMRS","IARS"],
    relations: ["colleague","family"],
    reason: "节日发到工位上不失礼，每杯还都用得上。" },
  { name: "高端鼠标 + 鼠标垫套装", searchQuery: "无线鼠标 礼盒 高端",
    priceMin: 400, priceMax: 700, priceTypical: 500, priceLabel: "¥400–700", emoji: "🖱️",
    tags: ["鼠标","办公","数码","桌面"],
    personas: ["IMRS","EMRS","IMRW"],
    relations: ["colleague","family","lover"],
    reason: "TA 每天点击 8000 次的那只——值得是好的那只。" },
  { name: "按摩抱枕（U 型护颈款）", searchQuery: "按摩抱枕 U型 颈椎",
    priceMin: 29, priceMax: 99, priceTypical: 36, priceLabel: "¥29–99", emoji: "💆",
    tags: ["按摩","颈椎","办公","健康"],
    personas: ["IMRS","IMLS","EMRS"],
    relations: ["colleague","family"],
    reason: "加班那 4 小时，靠它能挺过来。" },
  { name: "商务皮带 + 钱夹礼盒", searchQuery: "皮带 钱夹 礼盒",
    priceMin: 89, priceMax: 300, priceTypical: 220, priceLabel: "¥89–300", emoji: "👔",
    tags: ["皮带","钱夹","商务","真皮"],
    personas: ["EMRS","IMRS","EARS"],
    relations: ["colleague","family"],
    reason: "长辈、同事、男朋友都能用上的得体之选。" },
  { name: "颈肩按摩披肩（家用款）", searchQuery: "颈肩按摩披肩 家用",
    priceMin: 200, priceMax: 600, priceTypical: 350, priceLabel: "¥200–600", emoji: "💆",
    tags: ["按摩","颈肩","健康","长辈"],
    personas: ["IMLS","IALS","IARS"],
    relations: ["family","colleague"],
    reason: "长辈每天最舍得用 20 分钟的那一件。" },
  { name: "血压计 / 血糖仪（家用智能款）", searchQuery: "血压计 家用 智能",
    priceMin: 110, priceMax: 300, priceTypical: 200, priceLabel: "¥110–300", emoji: "🩺",
    tags: ["健康","监测","长辈","家用"],
    personas: ["IMLS","IMRS","IARS"],
    relations: ["family"],
    reason: "比一束花实在，比一通电话长久。" },
  { name: "按摩足浴桶（恒温智能款）", searchQuery: "足浴桶 恒温 智能",
    priceMin: 200, priceMax: 800, priceTypical: 400, priceLabel: "¥200–800", emoji: "🦶",
    tags: ["足浴","按摩","养生","长辈"],
    personas: ["IMLS","IALS","IARS"],
    relations: ["family","colleague"],
    reason: "每晚 20 分钟，TA 给自己的最大放纵。" },
  { name: "养生破壁料理机", searchQuery: "破壁料理机 养生",
    priceMin: 200, priceMax: 700, priceTypical: 400, priceLabel: "¥200–700", emoji: "🥣",
    tags: ["料理","养生","家电","健康"],
    personas: ["IMLS","IALS","IARS"],
    relations: ["family"],
    reason: "豆浆、粥、汤——长辈早上的那一锅。" },
  { name: "长辈防滑老花镜礼盒", searchQuery: "老花镜 礼盒 时尚",
    priceMin: 19, priceMax: 58, priceTypical: 29, priceLabel: "¥19–58", emoji: "👓",
    tags: ["老花镜","长辈","实用","礼盒"],
    personas: ["IARS","IMLS","IALS"],
    relations: ["family"],
    reason: "长辈翻报纸前最先找的那一副。" },
  { name: "轻奢羊绒围巾礼盒（男女款）", searchQuery: "羊绒围巾 礼盒",
    priceMin: 98, priceMax: 270, priceTypical: 150, priceLabel: "¥98–270", emoji: "🧣",
    tags: ["羊绒","围巾","保暖","得体"],
    personas: ["IARS","EARS","IMRS"],
    relations: ["family","colleague","lover"],
    reason: "冬天出门最得体的那一条，包住的不只是脖子。" },
  { name: "传统养生药枕（中药填充）", searchQuery: "中药 药枕 养生",
    priceMin: 42, priceMax: 99, priceTypical: 69, priceLabel: "¥42–99", emoji: "🛌",
    tags: ["药枕","中药","养生","长辈"],
    personas: ["IMLS","IARS","IALS"],
    relations: ["family"],
    reason: "长辈睡得稳，年轻人才能睡得安。" },
  { name: "高端保健品 / 维生素礼盒", searchQuery: "维生素 保健品 礼盒",
    priceMin: 99, priceMax: 380, priceTypical: 160, priceLabel: "¥99–380", emoji: "💊",
    tags: ["保健","维生素","长辈","礼盒"],
    personas: ["IMLS","IARS"],
    relations: ["family"],
    reason: "TA 自己舍不得买、却最该买的那一盒。" },
  { name: "老牌酒礼盒（茅台/五粮液小批量）", searchQuery: "白酒 礼盒 高端",
    priceMin: 1700, priceMax: 2700, priceTypical: 2200, priceLabel: "¥1700–2700", emoji: "🍶",
    tags: ["白酒","礼盒","长辈","商务"],
    personas: ["IARS","EMRS","EARS"],
    relations: ["family","colleague"],
    reason: "年节登门最稳的那一份。" },
  { name: "长辈智能手机大字版", searchQuery: "老人手机 大字 智能",
    priceMin: 300, priceMax: 600, priceTypical: 460, priceLabel: "¥300–600", emoji: "📱",
    tags: ["手机","长辈","智能","大字"],
    personas: ["IMRS","IMLS","IARS"],
    relations: ["family"],
    reason: "长辈也能看朋友圈点赞那种小幸福。" },
  { name: "小众设计师贴纸 / 文具杂货", searchQuery: "小众设计师 文具",
    priceMin: 10, priceMax: 40, priceTypical: 20, priceLabel: "¥10–40", emoji: "✏️",
    tags: ["文具","设计师","小众","轻"],
    personas: ["IMLW","EALW","IALW"],
    relations: ["crush","colleague","friend"],
    reason: "轻盈不越界，但已经够 TA 多看一眼。" },
  { name: "两人份精致下午茶礼券", searchQuery: "酒店下午茶 双人",
    priceMin: 300, priceMax: 600, priceTypical: 450, priceLabel: "¥300–600", emoji: "🍰",
    tags: ["下午茶","双人","礼券","约会"],
    personas: ["EARS","EALS","IMLS"],
    relations: ["crush","colleague","lover"],
    channel: "offline", channelHint: "大众点评 / 酒店官网",
    reason: "约 TA 出来吃这个，不是表白，但很接近。" },
  { name: "原木笔 + 笔筒桌面礼盒", searchQuery: "原木笔 礼盒 桌面",
    priceMin: 19, priceMax: 88, priceTypical: 39, priceLabel: "¥19–88", emoji: "🖊️",
    tags: ["原木","笔","桌面","得体"],
    personas: ["IMLW","IARS","IMRS"],
    relations: ["crush","colleague","family"],
    reason: "放在 TA 工位上的小心意，刚刚好。" },
  { name: "小众独立香氛卡片", searchQuery: "独立香氛 卡片",
    priceMin: 13, priceMax: 27, priceTypical: 20, priceLabel: "¥13–27", emoji: "🌸",
    tags: ["香氛","卡片","小众","清雅"],
    personas: ["EALS","IALS","EALW"],
    relations: ["crush","colleague","friend"],
    reason: "夹在书里、放在抽屉里，都是 TA 想起你的瞬间。" },
  { name: "双人份咖啡馆探店地图（城市文创）", searchQuery: "咖啡馆 地图 文创",
    priceMin: 20, priceMax: 80, priceTypical: 40, priceLabel: "¥20–80", emoji: "🗺️",
    tags: ["咖啡","地图","文创","探店"],
    personas: ["EALW","IALW","IMLW"],
    relations: ["crush","friend","colleague"],
    reason: "陪 TA 一家家走完，是这张地图的隐藏功能。" },
  { name: "生日数字蜡烛 + 仪式套装", searchQuery: "生日蜡烛 仪式 套装",
    priceMin: 15, priceMax: 50, priceTypical: 25, priceLabel: "¥15–50", emoji: "🕯️",
    tags: ["生日","仪式","蜡烛","布置"],
    personas: ["EARS","EMLS","EALS"],
    relations: ["lover","family","friend"],
    reason: "生日蛋糕上插着的那一根，决定整张照片的色调。" },
  { name: "生日礼物开箱仪式盒（多层惊喜）", searchQuery: "生日 多层 礼盒 惊喜",
    priceMin: 18, priceMax: 56, priceTypical: 25, priceLabel: "¥18–56", emoji: "🎁",
    tags: ["生日","仪式","惊喜","定制"],
    personas: ["EARS","EMLS","EALS"],
    relations: ["lover","family","friend"],
    reason: "TA 打开它要花 5 分钟——这 5 分钟全归你。" },
  { name: "星空生日定制礼盒（出生那天）", searchQuery: "星空 定制 生日 礼盒",
    priceMin: 31, priceMax: 200, priceTypical: 88, priceLabel: "¥31–200", emoji: "⭐",
    tags: ["星空","定制","生日","纪念"],
    personas: ["EARS","IARW","IALW"],
    relations: ["lover","family","crush"],
    reason: "TA 出生那天的天空——从此每年都能看一眼。" },
  { name: "乔迁香薰大礼盒（开运款）", searchQuery: "乔迁 香薰 礼盒",
    priceMin: 69, priceMax: 300, priceTypical: 150, priceLabel: "¥69–300", emoji: "🕯️",
    tags: ["乔迁","香薰","开运","礼盒"],
    personas: ["EALS","EARS","IALS"],
    relations: ["family","friend","colleague"],
    reason: "新房第一天的味道，从你送的这一盏开始。" },
  { name: "开门见福装饰画 / 中式挂件", searchQuery: "开门见福 挂件 装饰",
    priceMin: 13, priceMax: 88, priceTypical: 30, priceLabel: "¥13–88", emoji: "🪧",
    tags: ["乔迁","装饰","中式","开运"],
    personas: ["IARS","EARS","IALS"],
    relations: ["family","friend","colleague"],
    reason: "长辈最认这种心意，新房一进门就有了魂。" },
  { name: "全套茶水待客组（陶瓷茶具）", searchQuery: "待客茶具 套装",
    priceMin: 29, priceMax: 200, priceTypical: 88, priceLabel: "¥29–200", emoji: "🫖",
    tags: ["茶具","乔迁","待客","家居"],
    personas: ["IARS","EARS","IALS"],
    relations: ["family","friend","colleague"],
    reason: "新家第一拨客人坐下时，这套就该上场。" },
  { name: "高端开运摆件（铜器/水晶）", searchQuery: "铜器 开运 摆件",
    priceMin: 38, priceMax: 130, priceTypical: 55, priceLabel: "¥38–130", emoji: "🏯",
    tags: ["乔迁","摆件","开运","铜器"],
    personas: ["IARS","IARW","EARS"],
    relations: ["family","friend"],
    reason: "长辈最在意这件——TA 替 TA 操心了。" },
  { name: "中秋月饼 + 茶礼盒（高端联名）", searchQuery: "中秋 月饼 茶 礼盒",
    priceMin: 140, priceMax: 260, priceTypical: 220, priceLabel: "¥140–260", emoji: "🥮",
    tags: ["中秋","月饼","茶","节日"],
    personas: ["IARS","EARS","IMRS","EMRS"],
    relations: ["family","colleague","friend"],
    reason: "中秋送一件不踩雷的、又比月饼多一点的。" },
  { name: "春节年货大礼包（礼盒整箱）", searchQuery: "年货 礼盒 整箱",
    priceMin: 40, priceMax: 230, priceTypical: 100, priceLabel: "¥40–230", emoji: "🧧",
    tags: ["春节","年货","礼盒","节日"],
    personas: ["IARS","EARS","IMLS"],
    relations: ["family","colleague"],
    reason: "长辈、同事最实在的那种——年节登门必带。" },
  { name: "端午粽子高端礼盒", searchQuery: "端午 粽子 礼盒",
    priceMin: 39, priceMax: 170, priceTypical: 69, priceLabel: "¥39–170", emoji: "🍙",
    tags: ["端午","粽子","节日","礼盒"],
    personas: ["IARS","IMLS","EARS"],
    relations: ["family","colleague"],
    reason: "夏天最准时的那一盒。" },
  { name: "圣诞主题礼物盲盒（成人款）", searchQuery: "圣诞 盲盒 成人",
    priceMin: 50, priceMax: 200, priceTypical: 100, priceLabel: "¥50–200", emoji: "🎄",
    tags: ["圣诞","盲盒","节日","派对"],
    personas: ["EMLS","EALS","EMLW"],
    relations: ["friend","colleague","lover"],
    reason: "办公室交换礼物的那个，今年来真的。" },
  { name: "七夕 / 情人节定制对戒", searchQuery: "珠宝品牌店 对戒",
    priceMin: 600, priceMax: 1500, priceTypical: 1050, priceLabel: "¥600–1500", emoji: "💍",
    tags: ["对戒","情人节","定制","仪式"],
    personas: ["EARS","EALS","IMLW"],
    relations: ["lover"],
    channel: "offline", channelHint: "品牌门店 / 上手试戴",
    reason: "今年 TA 想等的，是不是就是这一刻。" },
  { name: "成人礼定制钢笔", searchQuery: "成人礼 钢笔 定制",
    priceMin: 38, priceMax: 170, priceTypical: 89, priceLabel: "¥38–170", emoji: "🖋️",
    tags: ["成人礼","钢笔","定制","仪式"],
    personas: ["EARS","IARS","IMRS"],
    relations: ["family","friend"],
    reason: "TA 第一份正式签字，希望发生在你送的笔上。" },
  { name: "毕业礼物盒（学位帽摆件）", searchQuery: "毕业 学位帽 摆件",
    priceMin: 20, priceMax: 100, priceTypical: 50, priceLabel: "¥20–100", emoji: "🎓",
    tags: ["毕业","学位帽","摆件","纪念"],
    personas: ["EARS","EMLS","IMLW"],
    relations: ["family","friend","colleague"],
    reason: "那一年的毕业季，从这只摆件开始永远存下来。" },
  { name: "轻奢公文包 + 商务皮带组（新人入职礼）", searchQuery: "公文包 皮带 商务礼盒",
    priceMin: 110, priceMax: 220, priceTypical: 190, priceLabel: "¥110–220", emoji: "💼",
    tags: ["入职","商务","公文包","成人礼"],
    personas: ["EMRS","IMRS","EARS"],
    relations: ["family","colleague"],
    reason: "TA 第一天上班，从这只包开始打仗。" },
  { name: "新生儿满月礼盒（金锁 / 银碗）", searchQuery: "新生儿 满月 礼盒",
    priceMin: 300, priceMax: 1500, priceTypical: 600, priceLabel: "¥300–1500", emoji: "👶",
    tags: ["新生儿","满月","金银","传统"],
    personas: ["IARS","EARS","IMLS"],
    relations: ["family","friend","colleague"],
    reason: "小宝宝戴上的第一件——传统、得体、有面子。" },
  { name: "婴儿成长记录定制相册", searchQuery: "婴儿 成长记录 相册",
    priceMin: 29, priceMax: 60, priceTypical: 39, priceLabel: "¥29–60", emoji: "📔",
    tags: ["婴儿","相册","成长","定制"],
    personas: ["EARS","EALS","IMLW"],
    relations: ["family","friend"],
    reason: "宝宝长大后翻到的第一段史料。" },
  { name: "CCD 复古卡片机 / 一次性胶卷相机", searchQuery: "CCD 卡片机 复古",
    priceMin: 99, priceMax: 600, priceTypical: 160, priceLabel: "¥99–600", emoji: "📸",
    tags: ["CCD","胶片","复古","记录"],
    personas: ["EMLS","EALW","EMLW"],
    relations: ["friend","lover","family"],
    reason: "每一场聚会的那张被贴在冰箱上的照片，从这里出来。" },
  { name: "温柔治愈系养生壶", searchQuery: "养生壶 多功能",
    priceMin: 60, priceMax: 120, priceTypical: 79, priceLabel: "¥60–120", emoji: "🍲",
    tags: ["养生壶","治愈","家电","健康"],
    personas: ["IMLS","IALS","IMRS"],
    relations: ["family","colleague","lover"],
    reason: "煮一壶花茶、一碗粥、一锅小火慢炖——一台搞定。" },
  { name: "高端钢笔收藏礼盒（万宝龙 / 公司定制款）", searchQuery: "万宝龙 钢笔 收藏礼盒",
    priceMin: 1400, priceMax: 4000, priceTypical: 2000, priceLabel: "¥1400–4000", emoji: "🖋️",
    tags: ["钢笔","收藏","商务","万宝龙"],
    personas: ["EMRS","IARS","EARS"],
    relations: ["family","lover","colleague"],
    reason: "TA 抽屉里压着 10 年的那一支。" },
  { name: "星盘定制装框挂画（按生日坑位）", searchQuery: "星盘 定制 挂画",
    priceMin: 80, priceMax: 300, priceTypical: 150, priceLabel: "¥80–300", emoji: "🌌",
    tags: ["星盘","定制","挂画","神秘"],
    personas: ["IARW","IALW","EALW"],
    relations: ["lover","friend","crush"],
    reason: "TA 出生那天的星空位置，装进相框里。" },
  { name: "古典守护者的茶饼礼盒（普洱十年陈）", searchQuery: "普洱 十年陈 茶饼",
    priceMin: 48, priceMax: 270, priceTypical: 98, priceLabel: "¥48–270", emoji: "🍵",
    tags: ["普洱","茶饼","收藏","古典"],
    personas: ["IARS","EMRS","IALS"],
    relations: ["family","colleague","lover"],
    reason: "TA 喝茶这 10 年的下一段故事，从这饼开始。" },
  { name: "赛博诗人的电子墨水手写板", searchQuery: "电子墨水 手写板",
    priceMin: 500, priceMax: 2000, priceTypical: 900, priceLabel: "¥500–2000", emoji: "📝",
    tags: ["手写板","数码","创作","电子墨水"],
    personas: ["IALW","IMRW","IMLW"],
    relations: ["lover","family","friend"],
    reason: "TA 想到的那句诗，写下来不会消失了。" },
  { name: "文艺冒险王的旅行册手账礼盒", searchQuery: "旅行手账 礼盒",
    priceMin: 18, priceMax: 68, priceTypical: 28, priceLabel: "¥18–68", emoji: "📔",
    tags: ["旅行","手账","礼盒","文艺"],
    personas: ["EALW","IALW","IMLW"],
    relations: ["lover","friend","family"],
    reason: "TA 这一年走过的城市，要一本能装下的本子。" }

];
